name: dust 
adopt-info: dust
summary: dust (du + rust = dust) is a alternative to 'du' written in rust.
description: |
  dust provides a fast way to see directories sizes on your device.
base: core20
grade: stable 
confinement: strict
license: MIT


architectures:
- build-on: amd64

apps:
  ncdu:
    aliases: 
      - ncdu
    command: ncdu


apps:
  dust:
    command: bin/dust
    plugs:
      - home
      - removable-media
      - mount-observe
      - system-backup # testing 

parts: 
  dust:
    source: https://github.com/bootandy/dust.git
    source-type: git
    plugin: rust
    
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git tag -l --sort=refname | tail -n 1)"
